CREATE DATABASE IF NOT EXISTS InnovaccerDB;

CREATE TABLE HOST_TABLE(
	NAME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40),
	PHONE VARCHAR(20) NOT NULL,
	PRIMARY KEY(EMAIL)
);

CREATE TABLE VISITOR_ENTRY(
	TOKEN int AUTO_INCREMENT,
	HOST_EMAIL VARCHAR(40),
	NAME VARCHAR(40),
	EMAIL VARCHAR(40),
	PHONE VARCHAR(20),
	ENTRY_DATE DATE,
	CHECKIN_HOUR int,
	CHECKIN_MIN int,
	CHECKOUT_HOUR int,
	CHECKOUT_MIN int,
	PRIMARY KEY(TOKEN)
);
