/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package innovaccersummergeeks;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Arrays;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.*;
import javax.mail.internet.*;

/**
 *
 * @author abhishek
 */
public class EntryManager extends javax.swing.JFrame {

    /**
     * Creates new form HostScreen
     */
    public EntryManager() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        showVisitorPanel.setVisible(true);
        this.setBackground(Color.BLACK);
        showVisitorLabel.setBackground(Color.WHITE);
        showTokenLabel.setBackground(Color.WHITE);
        
        variablePanel.removeAll();
        variablePanel.repaint();
        
        headingLabel.setText(VisitorEntry.colHeadings());
        VisitorEntry[] visitors = new VisitorEntry[0];
        visitorList.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return visitors.length;
            }

            public Object getElementAt(int i) {
                return visitors[i].toString();
            }
        });
        
        dbHandler = new DatabaseHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showVisitorLabel = new javax.swing.JLabel();
        showTokenLabel = new javax.swing.JLabel();
        checkinLabel = new javax.swing.JLabel();
        checkoutLabel = new javax.swing.JLabel();
        registerHostLabel = new javax.swing.JLabel();
        variablePanel = new javax.swing.JPanel();
        showVisitorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visitorList = new javax.swing.JList();
        headingLabel = new javax.swing.JLabel();
        checkoutPanel = new javax.swing.JPanel();
        tokenLabel = new javax.swing.JLabel();
        checkoutTimeLabel = new javax.swing.JLabel();
        tokenTextField = new javax.swing.JTextField();
        checkoutTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        checkinPanel = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        phoneLabel1 = new javax.swing.JLabel();
        checkinTimeLabel1 = new javax.swing.JLabel();
        hostEmail1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        hostEmailTextField1 = new javax.swing.JTextField();
        checkinTextField = new javax.swing.JTextField();
        checkinButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        registerHostPanel = new javax.swing.JPanel();
        hostNameLabel = new javax.swing.JLabel();
        hostEmailLabel = new javax.swing.JLabel();
        hostNameTextField = new javax.swing.JTextField();
        hostPhoneTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        hostPhoneLabel = new javax.swing.JLabel();
        hostEmailTextField = new javax.swing.JTextField();
        searchTokenPanel = new javax.swing.JPanel();
        nameLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        phoneLabel2 = new javax.swing.JLabel();
        checkinTimeLabel2 = new javax.swing.JLabel();
        hostEmail2 = new javax.swing.JLabel();
        showTokenTextField = new javax.swing.JTextField();
        showVisitorEmailTextField = new javax.swing.JTextField();
        showVisitorPhoneTextField = new javax.swing.JTextField();
        showHostEmailTextField = new javax.swing.JTextField();
        showCheckoutTextField = new javax.swing.JTextField();
        dateLabel1 = new javax.swing.JLabel();
        showDateTextField = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        showVisitorNameTextField = new javax.swing.JTextField();
        showCheckinTextField = new javax.swing.JTextField();
        checkinTimeLabel3 = new javax.swing.JLabel();
        checkinTimeLabel4 = new javax.swing.JLabel();
        showHostNameTextField = new javax.swing.JTextField();
        showHostPhoneTextField = new javax.swing.JTextField();
        hostEmail3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setBackground(new java.awt.Color(51, 51, 51));
        titleLabel.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Entry Management System");
        titleLabel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        showVisitorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showVisitorLabel.setForeground(new java.awt.Color(255, 255, 255));
        showVisitorLabel.setText("Show Visitors");
        showVisitorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showVisitorLabelMouseClicked(evt);
            }
        });

        showTokenLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showTokenLabel.setForeground(new java.awt.Color(255, 255, 255));
        showTokenLabel.setText("Search Token");
        showTokenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showTokenLabelMouseClicked(evt);
            }
        });

        checkinLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkinLabel.setText("Check-in");
        checkinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkinLabelMouseClicked(evt);
            }
        });

        checkoutLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkoutLabel.setText("Check-out");
        checkoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutLabelMouseClicked(evt);
            }
        });

        registerHostLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerHostLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerHostLabel.setText("Register Host");
        registerHostLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerHostLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTokenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showVisitorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(checkoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerHostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showVisitorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTokenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkoutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerHostLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        variablePanel.setLayout(new java.awt.CardLayout());

        showVisitorPanel.setBackground(new java.awt.Color(51, 51, 51));
        showVisitorPanel.setForeground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBorder(null);

        visitorList.setBackground(new java.awt.Color(51, 51, 51));
        visitorList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        visitorList.setForeground(new java.awt.Color(255, 255, 255));
        visitorList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        visitorList.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(visitorList);

        headingLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("jLabel1");

        javax.swing.GroupLayout showVisitorPanelLayout = new javax.swing.GroupLayout(showVisitorPanel);
        showVisitorPanel.setLayout(showVisitorPanelLayout);
        showVisitorPanelLayout.setHorizontalGroup(
            showVisitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showVisitorPanelLayout.createSequentialGroup()
                .addGroup(showVisitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(showVisitorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showVisitorPanelLayout.setVerticalGroup(
            showVisitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showVisitorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        variablePanel.add(showVisitorPanel, "card2");

        checkoutPanel.setBackground(new java.awt.Color(51, 51, 51));
        checkoutPanel.setForeground(new java.awt.Color(51, 51, 51));

        tokenLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tokenLabel.setForeground(new java.awt.Color(255, 255, 255));
        tokenLabel.setText("Token");

        checkoutTimeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkoutTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkoutTimeLabel.setText("Checkout  Time");

        tokenTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkoutTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tokenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokenLabel)
                    .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        variablePanel.add(checkoutPanel, "card2");

        checkinPanel.setBackground(new java.awt.Color(51, 51, 51));
        checkinPanel.setForeground(new java.awt.Color(51, 51, 51));

        nameLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel1.setText("Name");

        emailLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email");

        phoneLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel1.setText("Phone");

        checkinTimeLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinTimeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        checkinTimeLabel1.setText("Check-in Time");

        hostEmail1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostEmail1.setForeground(new java.awt.Color(255, 255, 255));
        hostEmail1.setText("Host Email");

        nameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        phoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        hostEmailTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkinTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkinButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinButton.setText("Submit");
        checkinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkinButtonMouseClicked(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date(YYYY-MM-DD)");

        dateTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout checkinPanelLayout = new javax.swing.GroupLayout(checkinPanel);
        checkinPanel.setLayout(checkinPanelLayout);
        checkinPanelLayout.setHorizontalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkinPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkinTimeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostEmailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(664, 664, 664))
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(checkinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkinPanelLayout.setVerticalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkinPanelLayout.createSequentialGroup()
                        .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel1)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinTimeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostEmailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkinButton)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        variablePanel.add(checkinPanel, "card2");

        registerHostPanel.setBackground(new java.awt.Color(51, 51, 51));
        registerHostPanel.setForeground(new java.awt.Color(51, 51, 51));

        hostNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        hostNameLabel.setText("Name");

        hostEmailLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        hostEmailLabel.setText("Email");

        hostNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        hostPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        hostPhoneLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        hostPhoneLabel.setText("Phone");

        hostEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout registerHostPanelLayout = new javax.swing.GroupLayout(registerHostPanel);
        registerHostPanel.setLayout(registerHostPanelLayout);
        registerHostPanelLayout.setHorizontalGroup(
            registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerHostPanelLayout.createSequentialGroup()
                .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerHostPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hostPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(hostNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hostEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hostEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hostPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerHostPanelLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        registerHostPanelLayout.setVerticalGroup(
            registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerHostPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        variablePanel.add(registerHostPanel, "card2");

        searchTokenPanel.setBackground(new java.awt.Color(51, 51, 51));
        searchTokenPanel.setForeground(new java.awt.Color(51, 51, 51));

        nameLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel2.setText("Token");

        emailLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel2.setText("Visitor Email");

        phoneLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneLabel2.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel2.setText("Visitor Phone");

        checkinTimeLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinTimeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        checkinTimeLabel2.setText("Check-out Time");

        hostEmail2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostEmail2.setForeground(new java.awt.Color(255, 255, 255));
        hostEmail2.setText("Host  Phone");

        showTokenTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showVisitorEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showVisitorPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showHostEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showCheckoutTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        dateLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel1.setText("Date(YYYY-MM-DD)");

        showDateTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        nameLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel3.setText("Visitor Name");

        showVisitorNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showCheckinTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkinTimeLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinTimeLabel3.setForeground(new java.awt.Color(255, 255, 255));
        checkinTimeLabel3.setText("Check-in Time");

        checkinTimeLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkinTimeLabel4.setForeground(new java.awt.Color(255, 255, 255));
        checkinTimeLabel4.setText("Host Name");

        showHostNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        showHostPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        hostEmail3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hostEmail3.setForeground(new java.awt.Color(255, 255, 255));
        hostEmail3.setText("Host Email");

        javax.swing.GroupLayout searchTokenPanelLayout = new javax.swing.GroupLayout(searchTokenPanel);
        searchTokenPanel.setLayout(searchTokenPanelLayout);
        searchTokenPanelLayout.setHorizontalGroup(
            searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTokenPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkinTimeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostEmail2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkinTimeLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkinTimeLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostEmail3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showHostPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showVisitorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHostEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showVisitorEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showVisitorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCheckoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCheckinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(664, 664, 664))
        );
        searchTokenPanelLayout.setVerticalGroup(
            searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTokenPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel2)
                    .addComponent(showTokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showVisitorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchTokenPanelLayout.createSequentialGroup()
                        .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showVisitorEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel2)
                            .addComponent(showVisitorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLabel1))
                .addGap(16, 16, 16)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCheckinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinTimeLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCheckoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinTimeLabel2))
                .addGap(18, 18, 18)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinTimeLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHostEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostEmail3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHostPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostEmail2))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        variablePanel.add(searchTokenPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(variablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showVisitorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showVisitorLabelMouseClicked
        variablePanel.removeAll();
        variablePanel.repaint();
        variablePanel.revalidate();
        
        variablePanel.add(showVisitorPanel);
        variablePanel.repaint();
        variablePanel.revalidate();
        
        VisitorEntry[] visitors = dbHandler.getEntryList();
        visitorList.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return visitors.length;
            }

            public Object getElementAt(int i) {
                return visitors[i].toString();
            }
        });
    }//GEN-LAST:event_showVisitorLabelMouseClicked

    private void showTokenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTokenLabelMouseClicked
        String s1 = JOptionPane.showInputDialog("Please enter the token to be searched : ");
        // TODO : get the Details from the token
        if(s1 != null){
            VisitorEntry e = dbHandler.getEntry(Integer.parseInt(s1));
            Host h = dbHandler.getHost(e.host_email);
            
            variablePanel.removeAll();
            variablePanel.repaint();
            variablePanel.revalidate();
            
            variablePanel.add(searchTokenPanel);
            variablePanel.repaint();
            variablePanel.revalidate();
            
            showTokenTextField.setText(String.format("%d", e.token));
            showTokenTextField.setEditable(false);
            
            showVisitorNameTextField.setText(e.visitor_name);
            showVisitorNameTextField.setEditable(false);
            
            showVisitorEmailTextField.setText(e.visitor_email);
            showVisitorEmailTextField.setEditable(false);
            
            showVisitorPhoneTextField.setText(e.visitor_phone);
            showVisitorPhoneTextField.setEditable(false);
            
            showDateTextField.setText(e.date);
            showDateTextField.setEditable(false);
            
            showCheckinTextField.setText(e.check_in);
            showCheckinTextField.setEditable(false);
            
            showCheckoutTextField.setText(e.check_out);
            showCheckoutTextField.setEditable(false);
            
            showHostNameTextField.setText(h.name);
            showHostNameTextField.setEditable(false);
            
            showHostEmailTextField.setText(h.email);
            showHostEmailTextField.setEditable(false);
            
            showHostPhoneTextField.setText(h.phone);
            showHostPhoneTextField.setEditable(false);
        }
    }//GEN-LAST:event_showTokenLabelMouseClicked

    private void checkinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinLabelMouseClicked
        variablePanel.removeAll();
        variablePanel.repaint();
        variablePanel.revalidate();
        
        variablePanel.add(checkinPanel);
        variablePanel.repaint();
        variablePanel.revalidate();
        
    }//GEN-LAST:event_checkinLabelMouseClicked

    private void checkoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutLabelMouseClicked
        variablePanel.removeAll();
        variablePanel.repaint();
        variablePanel.revalidate();
        
        variablePanel.add(checkoutPanel);
        variablePanel.repaint();
        variablePanel.revalidate();
        
    }//GEN-LAST:event_checkoutLabelMouseClicked

    private void registerHostLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerHostLabelMouseClicked
        variablePanel.removeAll();
        variablePanel.repaint();
        variablePanel.revalidate();

        variablePanel.add(registerHostPanel);
        variablePanel.repaint();
        variablePanel.revalidate();
    }//GEN-LAST:event_registerHostLabelMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int token = Integer.parseInt(tokenTextField.getText());
        dbHandler.updateCheckoutTime(token, checkoutTextField.getText());
        VisitorEntry v = dbHandler.getEntry(token);
        sendCheckoutEmail(v);
        try {
            sendSMS(v.visitor_phone, v.getCheckoutMail(dbHandler.getHost(v.host_email)));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Host host = new Host(hostNameTextField.getText(), hostEmailTextField.getText(), hostPhoneTextField.getText());
        dbHandler.insertHost(host);
    }//GEN-LAST:event_jButton3MouseClicked

    private void checkinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinButtonMouseClicked
        int token = dbHandler.insertEntry(
                new VisitorEntry(-1,
                hostEmailTextField1.getText(),
                nameTextField.getText(),
                emailTextField.getText(),
                phoneTextField.getText(),
                dateTextField.getText(),
                checkinTextField.getText(),
                null)
        );
        
        JOptionPane.showMessageDialog(rootPane, String.format("Entry token : %d", token));
        VisitorEntry v = dbHandler.getEntry(token);
        Host h = dbHandler.getHost(v.host_email);
        sendCheckinEmail(v);
        try{
            sendSMS(h.phone, v.getCheckinMail(h));
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_checkinButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryManager().setVisible(true);
            }
        });
        
    }
    
    private void sendCheckinEmail(VisitorEntry e){
        String from = "XXXXXXXXXX";
        String password = "XXXXXXXX";
        String[] to = {e.host_email};
        String subject = "Visitor Entry";
        String body = e.getCheckinMail(dbHandler.getHost(e.host_email));
        
        sendFromGMail(from, password, to, subject, body);
    }
    
    private void sendCheckoutEmail(VisitorEntry e){
        String from = "XXXXXXX";
        String password = "XXXXXXX";
        String[] to = {e.visitor_email};
        String subject = "Visitor Entry";
        String body = e.getCheckoutMail(dbHandler.getHost(e.host_email));
        
        sendFromGMail(from, password, to, subject, body);
    }
    
    
    private static void sendFromGMail(String from, String pass, String[] to, String subject, String body) {
        Properties props = System.getProperties();
        String host = "smtp.gmail.com";
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.user", from);
        props.put("mail.smtp.password", pass);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");

        Session session = Session.getDefaultInstance(props);
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(from));
            InternetAddress[] toAddress = new InternetAddress[to.length];

            // To get the array of addresses
            for( int i = 0; i < to.length; i++ ) {
                toAddress[i] = new InternetAddress(to[i]);
            }

            for( int i = 0; i < toAddress.length; i++) {
                message.addRecipient(Message.RecipientType.TO, toAddress[i]);
            }

            message.setSubject(subject);
            message.setText(body);
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
                        
        }
        catch (AddressException ae) {
            ae.printStackTrace();
        }
        catch (MessagingException me) {
            me.printStackTrace();
        }
    }
    
    private static void sendSMS(String phone, String body) throws Exception{
        String myURI = "https://api.bulksms.com/v1/messages";

        String myUsername = "cyxt3";
        String myPassword = "@QuickBrown123";
        
          String myData = "{to: \""+phone+"\", "
                  + "encoding: \"UNICODE\", "
                  + "body: \""+body+"\"}";
          
        URL url = new URL(myURI);
        HttpURLConnection request = (HttpURLConnection) url.openConnection();
        request.setDoOutput(true);

        // supply the credentials
        String authStr = myUsername + ":" + myPassword;
        String authEncoded = Base64.getEncoder().encodeToString(authStr.getBytes());
        request.setRequestProperty("Authorization", "Basic " + authEncoded);
        
        request.setRequestMethod("POST");
        request.setRequestProperty( "Content-Type", "application/json");

        // write the data to the request
        OutputStreamWriter out = new OutputStreamWriter(request.getOutputStream());
        out.write(myData);
        out.close();

        // try ... catch to handle errors nicely
        try {
        // make the call to the API
        InputStream response = request.getInputStream();
        BufferedReader in = new BufferedReader(new InputStreamReader(response));
        String replyText;
        while ((replyText = in.readLine()) != null) {
            System.out.println(replyText);
        }
        in.close();
    }   catch (IOException ex) {
        System.out.println("An error occurred:" + ex.getMessage());
            BufferedReader in = new BufferedReader(new InputStreamReader(request.getErrorStream()));
            // print the detail that comes with the error
            String replyText;
            while ((replyText = in.readLine()) != null) {
                System.out.println(replyText);
            }
            in.close();
        }
        request.disconnect();
    }

    private DatabaseHandler dbHandler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkinButton;
    private javax.swing.JLabel checkinLabel;
    private javax.swing.JPanel checkinPanel;
    private javax.swing.JTextField checkinTextField;
    private javax.swing.JLabel checkinTimeLabel1;
    private javax.swing.JLabel checkinTimeLabel2;
    private javax.swing.JLabel checkinTimeLabel3;
    private javax.swing.JLabel checkinTimeLabel4;
    private javax.swing.JLabel checkoutLabel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextField checkoutTextField;
    private javax.swing.JLabel checkoutTimeLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel hostEmail1;
    private javax.swing.JLabel hostEmail2;
    private javax.swing.JLabel hostEmail3;
    private javax.swing.JLabel hostEmailLabel;
    private javax.swing.JTextField hostEmailTextField;
    private javax.swing.JTextField hostEmailTextField1;
    private javax.swing.JLabel hostNameLabel;
    private javax.swing.JTextField hostNameTextField;
    private javax.swing.JLabel hostPhoneLabel;
    private javax.swing.JTextField hostPhoneTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel registerHostLabel;
    private javax.swing.JPanel registerHostPanel;
    private javax.swing.JPanel searchTokenPanel;
    private javax.swing.JTextField showCheckinTextField;
    private javax.swing.JTextField showCheckoutTextField;
    private javax.swing.JTextField showDateTextField;
    private javax.swing.JTextField showHostEmailTextField;
    private javax.swing.JTextField showHostNameTextField;
    private javax.swing.JTextField showHostPhoneTextField;
    private javax.swing.JLabel showTokenLabel;
    private javax.swing.JTextField showTokenTextField;
    private javax.swing.JTextField showVisitorEmailTextField;
    private javax.swing.JLabel showVisitorLabel;
    private javax.swing.JTextField showVisitorNameTextField;
    private javax.swing.JPanel showVisitorPanel;
    private javax.swing.JTextField showVisitorPhoneTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel tokenLabel;
    private javax.swing.JTextField tokenTextField;
    private javax.swing.JPanel variablePanel;
    private javax.swing.JList visitorList;
    // End of variables declaration//GEN-END:variables
}
